"""
Intercompany Elimination & Reconciliation Agent
Main orchestrator — entry point for end-to-end processing.

Author: Joel Stell, CPA MBA
Repository: github.com/JoelStell

Reads intercompany trial balance data from multiple legal entities,
matches IC pairs, identifies mismatches, generates elimination journal entries,
and uses the Anthropic Claude API for intelligent root cause analysis.
"""

import sys
import os
import time

# Ensure the script directory is on the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import config
import input_parser
import matching_engine
import je_generator
import ai_analyzer
import output_writer


def main():
    start_time = time.time()

    print("=" * 65)
    print("  INTERCOMPANY ELIMINATION & RECONCILIATION AGENT  v1.0")
    print(f"  Report Period: {config.REPORT_PERIOD}")
    print(f"  Report Date:   {config.REPORT_DATE}")
    print("=" * 65)

    # Step 1: Parse input
    print(f"\n[1/6] Parsing input workbook: {config.INPUT_FILE}")
    transactions, agreement_schedule = input_parser.parse_workbook(config.INPUT_FILE)

    # Step 2: Match and reconcile
    print(f"\n[2/6] Matching IC pairs and reconciling...")
    ic_pairs = matching_engine.match_and_reconcile(transactions, agreement_schedule)

    matched = [p for p in ic_pairs if p.match_status == "Matched"]
    errors = [p for p in ic_pairs if p.match_status != "Matched"]
    print(f"  Results: {len(matched)} clean matches, {len(errors)} findings")
    for pair in ic_pairs:
        status_icon = "✓" if pair.match_status == "Matched" else "✗"
        print(
            f"    {status_icon} {pair.entity_a_id} ↔ {pair.entity_b_id} "
            f"[{pair.transaction_type}] — {pair.match_status} "
            f"({pair.severity})"
        )

    # Step 3: Generate elimination JEs
    print(f"\n[3/6] Generating elimination journal entries...")
    journal_entries = je_generator.generate_entries(ic_pairs)

    auto = [j for j in journal_entries if j.status == "AutoGenerated"]
    review = [j for j in journal_entries if j.status == "RequiresReview"]
    blocked = [j for j in journal_entries if j.status == "Blocked"]
    print(f"  JEs generated: {len(auto)} auto, {len(review)} review, {len(blocked)} blocked")
    for je in journal_entries:
        bal = "BAL" if je.is_balanced else "UNBAL"
        print(f"    {je.je_number}: {je.status} [{bal}] — {je.description}")

    # Step 4: AI analysis
    print(f"\n[4/6] Running AI analysis on {len(errors)} findings...")
    findings, exec_summary = ai_analyzer.analyze_all(ic_pairs)

    # Step 5: Write Excel output
    print(f"\n[5/6] Writing Excel report: {config.OUTPUT_EXCEL}")
    output_writer.write_excel(ic_pairs, journal_entries, findings)

    # Step 6: Write markdown summary
    print(f"\n[6/6] Writing markdown summary: {config.OUTPUT_MARKDOWN}")
    output_writer.write_markdown_summary(
        ic_pairs, journal_entries, findings, exec_summary
    )

    elapsed = time.time() - start_time
    print(f"\n{'=' * 65}")
    print(f"  COMPLETE — {elapsed:.1f}s elapsed")
    print(f"  Output files:")
    print(f"    - {config.OUTPUT_EXCEL}")
    print(f"    - {config.OUTPUT_MARKDOWN}")
    print(f"{'=' * 65}")


if __name__ == "__main__":
    main()
