"""
Elimination Journal Entry Generator.
Produces elimination JEs for matched pairs and partial JEs for reviewable mismatches.
Blocks JE generation for errors that require manual resolution.
"""

from decimal import Decimal
from typing import List
from models import ICPair, EliminationJE, JELine
import config


_je_counter = 0


def generate_entries(ic_pairs: List[ICPair]) -> List[EliminationJE]:
    global _je_counter
    _je_counter = 0
    entries = []

    for pair in ic_pairs:
        je = _generate_for_pair(pair)
        if je:
            entries.append(je)

    # Validate all generated JEs balance
    for je in entries:
        if not je.is_balanced:
            je.notes += f" WARNING: JE does not balance. DR={je.total_debits}, CR={je.total_credits}."
            je.status = "RequiresReview"

    return entries


def _next_je_number() -> str:
    global _je_counter
    _je_counter += 1
    return f"ELIM-{_je_counter:03d}"


def _generate_for_pair(pair: ICPair) -> EliminationJE:
    if pair.match_status == "Matched":
        return _generate_clean_elimination(pair)
    elif pair.match_status == "Mismatch" and pair.error_category == "Settlement":
        return _generate_partial_elimination(pair)
    elif pair.match_status == "Mismatch" and pair.error_category == "FX":
        return _generate_fx_mismatch_elimination(pair)
    elif pair.match_status == "Mismatch" and pair.error_category == "Classification":
        return _generate_blocked_entry(pair, "Account classification mismatch")
    elif pair.match_status == "OneSided":
        return _generate_blocked_entry(pair, "One-sided posting")
    elif pair.match_status == "Unauthorized":
        return _generate_blocked_entry(pair, "Unauthorized IC pair")
    return None


def _generate_clean_elimination(pair: ICPair) -> EliminationJE:
    """Full elimination for a clean match."""
    je = EliminationJE(
        je_number=_next_je_number(),
        description=f"Eliminate IC {pair.transaction_type} - {pair.entity_a_id} / {pair.entity_b_id}",
        entity_a=pair.entity_a_id,
        entity_b=pair.entity_b_id,
        ic_transaction_type=pair.transaction_type,
        source_pair=pair,
        status="AutoGenerated",
    )

    amt = pair.entity_a_total_usd  # Both sides equal for clean match
    accounts = config.EXPECTED_ACCOUNTS.get(pair.transaction_type, {})

    if pair.transaction_type == "Trade":
        # Eliminate P&L: DR Revenue, CR COGS
        je.lines.append(JELine(accounts["revenue"],
                                config.CHART_OF_ACCOUNTS.get(accounts["revenue"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["cogs"],
                                config.CHART_OF_ACCOUNTS.get(accounts["cogs"], ""),
                                Decimal("0"), amt))
        # Eliminate BS: DR Payable, CR Receivable
        je.lines.append(JELine(accounts["payable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["receivable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                Decimal("0"), amt))

    elif pair.transaction_type == "MgmtFee":
        je.lines.append(JELine(accounts["revenue"],
                                config.CHART_OF_ACCOUNTS.get(accounts["revenue"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["expense"],
                                config.CHART_OF_ACCOUNTS.get(accounts["expense"], ""),
                                Decimal("0"), amt))
        je.lines.append(JELine(accounts["payable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["receivable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                Decimal("0"), amt))

    elif pair.transaction_type == "Dividend":
        je.lines.append(JELine(accounts["equity_paid"],
                                config.CHART_OF_ACCOUNTS.get(accounts["equity_paid"], ""),
                                Decimal("0"), amt))
        je.lines.append(JELine(accounts["equity_received"],
                                config.CHART_OF_ACCOUNTS.get(accounts["equity_received"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["payable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["receivable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                Decimal("0"), amt))

    elif pair.transaction_type == "Loan":
        # Loan elimination is BS only: DR Payable, CR Receivable
        je.lines.append(JELine(accounts["payable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["receivable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                Decimal("0"), amt))

    je.notes = "Clean match. Full elimination auto-generated."
    return je


def _generate_partial_elimination(pair: ICPair) -> EliminationJE:
    """Partial elimination at the agreed amount (lower of two sides)."""
    agreed_amt = min(pair.entity_a_total_usd, pair.entity_b_total_usd)
    diff = pair.net_difference

    je = EliminationJE(
        je_number=_next_je_number(),
        description=(
            f"Partial eliminate IC {pair.transaction_type} - "
            f"{pair.entity_a_id} / {pair.entity_b_id} "
            f"(${diff:,.2f} difference under review)"
        ),
        entity_a=pair.entity_a_id,
        entity_b=pair.entity_b_id,
        ic_transaction_type=pair.transaction_type,
        source_pair=pair,
        status="RequiresReview",
    )

    accounts = config.EXPECTED_ACCOUNTS.get(pair.transaction_type, {})

    if pair.transaction_type == "Loan":
        je.lines.append(JELine(accounts["payable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                agreed_amt, Decimal("0")))
        je.lines.append(JELine(accounts["receivable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                Decimal("0"), agreed_amt))
    else:
        # Generic: eliminate at agreed amount
        if "revenue" in accounts and "cogs" in accounts:
            je.lines.append(JELine(accounts["revenue"],
                                    config.CHART_OF_ACCOUNTS.get(accounts["revenue"], ""),
                                    agreed_amt, Decimal("0")))
            je.lines.append(JELine(accounts["cogs"],
                                    config.CHART_OF_ACCOUNTS.get(accounts["cogs"], ""),
                                    Decimal("0"), agreed_amt))
        if "payable" in accounts and "receivable" in accounts:
            je.lines.append(JELine(accounts["payable"],
                                    config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                    agreed_amt, Decimal("0")))
            je.lines.append(JELine(accounts["receivable"],
                                    config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                    Decimal("0"), agreed_amt))

    je.notes = (
        f"Partial elimination at confirmed amount of ${agreed_amt:,.2f}. "
        f"Remaining difference of ${diff:,.2f} requires investigation. "
        f"Entities report different settlement amounts."
    )
    return je


def _generate_fx_mismatch_elimination(pair: ICPair) -> EliminationJE:
    """Elimination for FX rate mismatch — both sides show same USD but different rates."""
    amt = min(pair.entity_a_total_usd, pair.entity_b_total_usd)

    je = EliminationJE(
        je_number=_next_je_number(),
        description=(
            f"Eliminate IC {pair.transaction_type} - "
            f"{pair.entity_a_id} / {pair.entity_b_id} "
            f"(FX rate discrepancy flagged)"
        ),
        entity_a=pair.entity_a_id,
        entity_b=pair.entity_b_id,
        ic_transaction_type=pair.transaction_type,
        source_pair=pair,
        status="RequiresReview",
    )

    accounts = config.EXPECTED_ACCOUNTS.get(pair.transaction_type, {})

    if pair.transaction_type == "Trade":
        je.lines.append(JELine(accounts["revenue"],
                                config.CHART_OF_ACCOUNTS.get(accounts["revenue"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["cogs"],
                                config.CHART_OF_ACCOUNTS.get(accounts["cogs"], ""),
                                Decimal("0"), amt))
        je.lines.append(JELine(accounts["payable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["payable"], ""),
                                amt, Decimal("0")))
        je.lines.append(JELine(accounts["receivable"],
                                config.CHART_OF_ACCOUNTS.get(accounts["receivable"], ""),
                                Decimal("0"), amt))

    rate_a = pair.fx_rate_a or Decimal("0")
    rate_b = pair.fx_rate_b or Decimal("0")
    je.notes = (
        f"USD amounts match at ${amt:,.2f}, but entities used different FX rates: "
        f"{pair.entity_a_id} rate={rate_a}, {pair.entity_b_id} rate={rate_b}. "
        f"Per ASC 830-10-45, entities in the same IC transaction should use "
        f"consistent exchange rates. FX gain/loss impact at next revaluation "
        f"requires Treasury review."
    )
    return je


def _generate_blocked_entry(pair: ICPair, reason: str) -> EliminationJE:
    """Blocked JE — documents why elimination cannot proceed."""
    je = EliminationJE(
        je_number=_next_je_number(),
        description=(
            f"BLOCKED: IC {pair.transaction_type} - "
            f"{pair.entity_a_id} / {pair.entity_b_id}"
        ),
        entity_a=pair.entity_a_id,
        entity_b=pair.entity_b_id,
        ic_transaction_type=pair.transaction_type,
        source_pair=pair,
        status="Blocked",
    )

    if pair.error_category == "OneSided":
        posting_entity = pair.entity_a_id if pair.entity_a_transactions else pair.entity_b_id
        missing_entity = pair.entity_b_id if pair.entity_a_transactions else pair.entity_a_id
        amt = pair.entity_a_total_usd if pair.entity_a_transactions else pair.entity_b_total_usd
        je.notes = (
            f"Elimination blocked: {posting_entity} has IC {pair.transaction_type} "
            f"balance of ${amt:,.2f} with {missing_entity}, but {missing_entity} "
            f"has no offsetting entry. Cannot eliminate a one-sided posting. "
            f"Action required: {missing_entity} must book the offsetting entry "
            f"or {posting_entity} must reverse the orphan posting."
        )
    elif pair.error_category == "Classification":
        je.notes = (
            f"Elimination blocked: Account classification mismatch. "
            f"USD amounts agree but account codes used do not match expected "
            f"mappings for {pair.transaction_type} transactions. "
            f"Generating elimination JE against incorrect accounts would "
            f"misstate the consolidated trial balance. "
            f"Action required: Reclassify to correct IC accounts before elimination."
        )
    elif pair.error_category == "Unauthorized":
        je.notes = (
            f"Elimination blocked: IC pair {pair.entity_a_id} / {pair.entity_b_id} "
            f"for transaction type '{pair.transaction_type}' is not listed on the "
            f"IC Agreement Schedule. This transaction requires investigation. "
            f"Per ASC 850-10, unauthorized related party transactions may require "
            f"disclosure. Action required: Obtain retroactive authorization or reverse."
        )
    else:
        je.notes = f"Elimination blocked: {reason}."

    return je
