"""
Data models for the Intercompany Elimination & Reconciliation Agent.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import List, Optional


@dataclass
class ICTransaction:
    transaction_id: str
    entity_id: str
    partner_entity_id: str
    account_code: str
    account_name: str
    transaction_type: str
    description: str
    local_currency: str
    local_amount: Decimal
    fx_rate: Decimal
    usd_amount: Decimal
    settlement_status: str
    reference_number: str
    posting_date: str
    explanation: str


@dataclass
class JELine:
    account_code: str
    account_name: str
    debit: Decimal
    credit: Decimal


@dataclass
class ICPair:
    entity_a_id: str
    entity_b_id: str
    transaction_type: str
    entity_a_transactions: List[ICTransaction] = field(default_factory=list)
    entity_b_transactions: List[ICTransaction] = field(default_factory=list)
    entity_a_total_usd: Decimal = Decimal("0")
    entity_b_total_usd: Decimal = Decimal("0")
    net_difference: Decimal = Decimal("0")
    is_authorized: bool = True
    match_status: str = "Pending"
    error_category: str = "None"
    severity: str = "Clean"
    fx_rate_a: Optional[Decimal] = None
    fx_rate_b: Optional[Decimal] = None
    account_code_a: Optional[str] = None
    account_code_b: Optional[str] = None


@dataclass
class EliminationJE:
    je_number: str
    description: str
    entity_a: str
    entity_b: str
    lines: List[JELine] = field(default_factory=list)
    ic_transaction_type: str = ""
    source_pair: Optional[ICPair] = None
    status: str = "AutoGenerated"
    notes: str = ""

    @property
    def total_debits(self) -> Decimal:
        return sum(line.debit for line in self.lines)

    @property
    def total_credits(self) -> Decimal:
        return sum(line.credit for line in self.lines)

    @property
    def is_balanced(self) -> bool:
        return abs(self.total_debits - self.total_credits) < Decimal("0.01")


@dataclass
class Finding:
    finding_id: str
    ic_pair: ICPair
    error_category: str
    entity_a_data: dict = field(default_factory=dict)
    entity_b_data: dict = field(default_factory=dict)
    difference_usd: Decimal = Decimal("0")
    root_cause: str = ""
    impact_assessment: str = ""
    recommended_resolution: str = ""
    asc_reference: str = ""
    priority: int = 3
    ai_validation_warnings: List[str] = field(default_factory=list)
    ai_validated: bool = False
