"""
Output Writer — produces the Excel elimination report and markdown summary.
Three Excel tabs: Recon Summary, Elimination JEs, Mismatch Detail.
One markdown executive summary file.
"""

from decimal import Decimal
from typing import List
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from models import ICPair, EliminationJE, Finding
import config


# --- Styles ---
HEADER_FONT = Font(name="Arial", bold=True, size=10, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="2F5496")
DATA_FONT = Font(name="Arial", size=10)
TITLE_FONT = Font(name="Arial", bold=True, size=14, color="2F5496")
THIN_BORDER = Border(
    left=Side(style="thin", color="D9D9D9"),
    right=Side(style="thin", color="D9D9D9"),
    top=Side(style="thin", color="D9D9D9"),
    bottom=Side(style="thin", color="D9D9D9"),
)

SEVERITY_COLORS = {
    "Clean": PatternFill("solid", fgColor="C6EFCE"),
    "Low": PatternFill("solid", fgColor="DDEBF7"),
    "Medium": PatternFill("solid", fgColor="FFF2CC"),
    "High": PatternFill("solid", fgColor="FCE4D6"),
    "Critical": PatternFill("solid", fgColor="F4CCCC"),
}

STATUS_COLORS = {
    "AutoGenerated": PatternFill("solid", fgColor="C6EFCE"),
    "RequiresReview": PatternFill("solid", fgColor="FFF2CC"),
    "Blocked": PatternFill("solid", fgColor="F4CCCC"),
}

USD_FMT = '#,##0.00'


def _style_header(ws, headers):
    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
        cell.border = THIN_BORDER


def _write_cell(ws, row, col, value, fmt=None, fill=None):
    cell = ws.cell(row=row, column=col, value=value)
    cell.font = DATA_FONT
    cell.border = THIN_BORDER
    if fmt:
        cell.number_format = fmt
    if fill:
        cell.fill = fill
    return cell


def _set_col_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def write_excel(
    ic_pairs: List[ICPair],
    journal_entries: List[EliminationJE],
    findings: List[Finding],
    filepath: str = None,
):
    filepath = filepath or config.OUTPUT_EXCEL
    wb = Workbook()

    _write_recon_summary(wb, ic_pairs, findings)
    _write_elimination_jes(wb, journal_entries)
    _write_mismatch_detail(wb, findings)

    wb.save(filepath)
    print(f"  Output Excel saved: {filepath}")


def _write_recon_summary(wb: Workbook, ic_pairs: List[ICPair], findings: List[Finding]):
    ws = wb.active
    ws.title = "Recon Summary"

    headers = [
        "IC Pair", "Transaction Type",
        "Entity A Balance (USD)", "Entity B Balance (USD)",
        "Net Difference (USD)", "Match Status", "Severity",
        "Error Category", "AI Flag", "AI Commentary",
        "ASC Reference", "Resolution Action",
    ]
    _style_header(ws, headers)

    # Build findings lookup
    findings_map = {}
    for f in findings:
        key = (f.ic_pair.entity_a_id, f.ic_pair.entity_b_id, f.ic_pair.transaction_type)
        findings_map[key] = f

    for row_idx, pair in enumerate(ic_pairs, start=2):
        pair_label = f"{pair.entity_a_id} ↔ {pair.entity_b_id}"
        key = (pair.entity_a_id, pair.entity_b_id, pair.transaction_type)
        finding = findings_map.get(key)
        has_ai = "Y" if finding else "N"
        commentary = finding.root_cause if finding else "No issues identified."
        asc_ref = finding.asc_reference if finding else ""
        resolution = finding.recommended_resolution if finding else ""

        severity_fill = SEVERITY_COLORS.get(pair.severity)

        _write_cell(ws, row_idx, 1, pair_label)
        _write_cell(ws, row_idx, 2, pair.transaction_type)
        _write_cell(ws, row_idx, 3, float(pair.entity_a_total_usd), fmt=USD_FMT)
        _write_cell(ws, row_idx, 4, float(pair.entity_b_total_usd), fmt=USD_FMT)
        _write_cell(ws, row_idx, 5, float(pair.net_difference), fmt=USD_FMT)
        _write_cell(ws, row_idx, 6, pair.match_status)
        _write_cell(ws, row_idx, 7, pair.severity, fill=severity_fill)
        _write_cell(ws, row_idx, 8, pair.error_category)
        _write_cell(ws, row_idx, 9, has_ai)
        _write_cell(ws, row_idx, 10, commentary)
        _write_cell(ws, row_idx, 11, asc_ref)
        _write_cell(ws, row_idx, 12, resolution)

    _set_col_widths(ws, [22, 16, 22, 22, 22, 16, 12, 16, 8, 55, 40, 55])
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions


def _write_elimination_jes(wb: Workbook, journal_entries: List[EliminationJE]):
    ws = wb.create_sheet("Elimination JEs")

    headers = [
        "JE Number", "Description", "Entity A", "Entity B",
        "Account Code", "Account Name", "Debit (USD)", "Credit (USD)",
        "IC Transaction Type", "Status", "Notes",
    ]
    _style_header(ws, headers)

    row_idx = 2
    for je in journal_entries:
        status_fill = STATUS_COLORS.get(je.status)

        if je.lines:
            for i, line in enumerate(je.lines):
                _write_cell(ws, row_idx, 1, je.je_number if i == 0 else "")
                _write_cell(ws, row_idx, 2, je.description if i == 0 else "")
                _write_cell(ws, row_idx, 3, je.entity_a if i == 0 else "")
                _write_cell(ws, row_idx, 4, je.entity_b if i == 0 else "")
                _write_cell(ws, row_idx, 5, line.account_code)
                _write_cell(ws, row_idx, 6, line.account_name)
                _write_cell(ws, row_idx, 7, float(line.debit) if line.debit else "", fmt=USD_FMT)
                _write_cell(ws, row_idx, 8, float(line.credit) if line.credit else "", fmt=USD_FMT)
                _write_cell(ws, row_idx, 9, je.ic_transaction_type if i == 0 else "")
                _write_cell(ws, row_idx, 10, je.status if i == 0 else "", fill=status_fill if i == 0 else None)
                _write_cell(ws, row_idx, 11, je.notes if i == 0 else "")
                row_idx += 1
        else:
            # Blocked entries with no lines
            _write_cell(ws, row_idx, 1, je.je_number)
            _write_cell(ws, row_idx, 2, je.description)
            _write_cell(ws, row_idx, 3, je.entity_a)
            _write_cell(ws, row_idx, 4, je.entity_b)
            _write_cell(ws, row_idx, 5, "—")
            _write_cell(ws, row_idx, 6, "No JE lines — see Notes")
            _write_cell(ws, row_idx, 7, "")
            _write_cell(ws, row_idx, 8, "")
            _write_cell(ws, row_idx, 9, je.ic_transaction_type)
            _write_cell(ws, row_idx, 10, je.status, fill=status_fill)
            _write_cell(ws, row_idx, 11, je.notes)
            row_idx += 1

        # Blank separator row between JEs
        row_idx += 1

    _set_col_widths(ws, [12, 40, 12, 12, 12, 30, 18, 18, 16, 16, 60])
    ws.freeze_panes = "A2"


def _write_mismatch_detail(wb: Workbook, findings: List[Finding]):
    ws = wb.create_sheet("Mismatch Detail")

    headers = [
        "Finding ID", "IC Pair", "Transaction Type", "Error Category",
        "Entity A Data", "Entity B Data", "Difference (USD)",
        "Root Cause Analysis", "Impact Assessment",
        "Recommended Resolution", "ASC Reference", "Priority",
    ]
    _style_header(ws, headers)

    for row_idx, f in enumerate(findings, start=2):
        pair = f.ic_pair
        pair_label = f"{pair.entity_a_id} ↔ {pair.entity_b_id}"

        a_summary = _summarize_entity_data(f.entity_a_data)
        b_summary = _summarize_entity_data(f.entity_b_data)

        priority_fill = None
        if f.priority == 1:
            priority_fill = PatternFill("solid", fgColor="F4CCCC")
        elif f.priority == 2:
            priority_fill = PatternFill("solid", fgColor="FFF2CC")

        _write_cell(ws, row_idx, 1, f.finding_id)
        _write_cell(ws, row_idx, 2, pair_label)
        _write_cell(ws, row_idx, 3, pair.transaction_type)
        _write_cell(ws, row_idx, 4, pair.error_category)
        _write_cell(ws, row_idx, 5, a_summary)
        _write_cell(ws, row_idx, 6, b_summary)
        _write_cell(ws, row_idx, 7, float(f.difference_usd), fmt=USD_FMT)
        _write_cell(ws, row_idx, 8, f.root_cause)
        _write_cell(ws, row_idx, 9, f.impact_assessment)
        _write_cell(ws, row_idx, 10, f.recommended_resolution)
        _write_cell(ws, row_idx, 11, f.asc_reference)
        _write_cell(ws, row_idx, 12, f.priority, fill=priority_fill)

    _set_col_widths(ws, [12, 22, 16, 16, 45, 45, 18, 55, 55, 55, 40, 10])
    ws.freeze_panes = "A2"


def _summarize_entity_data(data: dict) -> str:
    if not data.get("transactions"):
        return f"{data.get('entity_id', 'N/A')}: No transactions booked"

    lines = [f"{data['entity_id']} ({data.get('entity_name', '')})"]
    lines.append(f"Total USD: ${data['total_usd']:,.2f}")
    if data.get("fx_rate") and data["fx_rate"] != 1.0:
        lines.append(f"FX Rate: {data['fx_rate']}")
    for t in data["transactions"]:
        lines.append(f"  {t['id']}: {t['account']} ${t['usd_amount']:,.2f}")
    return "\n".join(lines)


def write_markdown_summary(
    ic_pairs: List[ICPair],
    journal_entries: List[EliminationJE],
    findings: List[Finding],
    exec_summary: str,
    filepath: str = None,
):
    filepath = filepath or config.OUTPUT_MARKDOWN

    matched = [p for p in ic_pairs if p.match_status == "Matched"]
    auto_jes = [j for j in journal_entries if j.status == "AutoGenerated"]
    review_jes = [j for j in journal_entries if j.status == "RequiresReview"]
    blocked_jes = [j for j in journal_entries if j.status == "Blocked"]

    total_matched_usd = sum(p.entity_a_total_usd for p in matched)
    total_findings_usd = sum(f.difference_usd for f in findings)

    md = exec_summary + "\n\n"

    md += "---\n\n"
    md += "### Elimination JE Summary\n\n"
    md += f"| JE Number | Type | Entities | Amount (USD) | Status |\n"
    md += f"|-----------|------|----------|-------------|--------|\n"
    for je in journal_entries:
        amt = f"${je.total_debits:,.2f}" if je.total_debits > 0 else "N/A"
        md += f"| {je.je_number} | {je.ic_transaction_type} | {je.entity_a} / {je.entity_b} | {amt} | {je.status} |\n"

    md += "\n---\n\n"
    md += "### ASC Compliance Notes\n\n"
    md += (
        "- **ASC 810-10** — Consolidation: All intercompany balances and transactions "
        "must be eliminated in the consolidated financial statements.\n"
        "- **ASC 830-10-45** — Foreign Currency: Transaction gains and losses from IC "
        "balances denominated in a currency other than the entity's functional currency "
        "must be recognized in income. Entities in the same IC transaction should use "
        "consistent exchange rates.\n"
        "- **ASC 850-10-50** — Related Party Disclosures: Unauthorized IC transactions "
        "may trigger additional disclosure requirements.\n"
    )

    md += "\n---\n\n"
    md += (
        f"*Report generated by Intercompany Elimination & Reconciliation Agent v1.0*\n"
        f"*Author: Joel Stell, CPA MBA*\n"
    )

    with open(filepath, "w") as f:
        f.write(md)

    print(f"  Markdown summary saved: {filepath}")
